apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-rule
  namespace: {{.Values.namespace}}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: accountservice
          servicePort: 8081
        path: /api/account
      - backend:
          serviceName: customerservice
          servicePort: 8084
        path: /api/customer
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/customerEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/accountEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/loanEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/beneficiaryEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/creditCardEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/accountproductEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/fundsEnquiry
      - backend:
          serviceName: moneymgmt
          servicePort: 8087
        path: /api/money_management
      - backend:
          serviceName: loanservice
          servicePort: 8086
        path: /api/loan-management
      - backend:
          serviceName: beneficiariesservice
          servicePort: 8082
        path: /api/beneficiary
      - backend:
          serviceName: gsservice
          servicePort: 6050
        path: /api/gs
      - backend:
          serviceName: leadservice
          servicePort: 8091
        path: /api/lead
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/eventStore
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/guarantors
      - backend:
          serviceName: loanservice
          servicePort: 8086
        path: /api/loan
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/termDepositeEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/taxEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/depositAccruedEnquiry
      - backend:
          serviceName: enquiryservice
          servicePort: 8085
        path: /api/leadEnquiry
      - backend:
          serviceName: productservice
          servicePort: 8089
        path: /api/savingProduct
      - backend:
          serviceName: productservice
          servicePort: 8089
        path: /api/taxConfig
